@amount = 500
@senderAccountNumber = "10203810400000000005"
@receiverAccountNumber = "10203810400000000005"

###
POST http://localhost:8080/api/transfers/deposit
Content-Type: application/json

{
  "amount": {{amount}},
  "senderAccountNumber": "",
  "receiverAccountNumber": {{receiverAccountNumber}}
}


###
POST http://localhost:8080/api/transfers/transfer
Content-Type: application/json

{
  "amount": {{amount}},
  "senderAccountNumber": {{senderAccountNumber}},
  "receiverAccountNumber": {{receiverAccountNumber}}
}